id = "5a5df514-379c-42f9-8746-fee8a119ed5c"
images = []
files = []
format = "notes/v1"

[[notes]]
file = "./agent-skills.toml"

[[notes]]
title = "Preparation"
id = "093d6598-63cf-4423-92c5-9703464817a7"
type = "text"
order = 1
icon_emoji = "📚"
text = ""

[[notes]]
title = "Study Notes"
id = "65486a33-c25e-4f0e-960d-0131c91ac1c1"
type = "text"
parent = "093d6598-63cf-4423-92c5-9703464817a7"
order = 1
icon_emoji = "📖"
text = """Techniques, methodology, and resources from your preparation...

"""

[[notes]]
title = "Lab Notes"
id = "1b8acbd6-f3aa-4fc9-ae89-54bb73076228"
type = "text"
parent = "093d6598-63cf-4423-92c5-9703464817a7"
order = 2
icon_emoji = "🧪"
text = """Notes and progress from lab machines...

"""

[[notes]]
title = "To Do's"
id = "7c2d41a6-950b-4f75-a350-fce566951f70"
type = "text"
parent = "093d6598-63cf-4423-92c5-9703464817a7"
order = 3
icon_emoji = "✔️"
text = ""

[[notes]]
title = "To Do X"
id = "d9090231-a2a4-4784-b62e-d9ace07638d0"
type = "text"
parent = "7c2d41a6-950b-4f75-a350-fce566951f70"
order = 1
checked = false
text = ""

[[notes]]
title = "Exam"
id = "2c932ba1-11cf-4e23-bbe1-a65235513872"
type = "text"
order = 2
icon_emoji = "🎯"
text = ""

[[notes]]
title = "Exam Info"
id = "3deb317e-3580-472b-8a3d-951c14d706e9"
type = "text"
parent = "2c932ba1-11cf-4e23-bbe1-a65235513872"
order = 1
icon_emoji = "ℹ️"
text = """# Exam Details
OSID, VPN connection, start time, and exam rules reminders...

"""

[[notes]]
title = "Targets"
id = "a1af6eb1-2adf-44f9-a1cc-4ac0830fc72c"
type = "text"
parent = "2c932ba1-11cf-4e23-bbe1-a65235513872"
order = 2
icon_emoji = "💻"
text = ""

[[notes]]
title = "Target X"
id = "0915eb97-ddaf-484a-9354-cef15e60dbe4"
type = "text"
parent = "a1af6eb1-2adf-44f9-a1cc-4ac0830fc72c"
order = 1
checked = false
text = ""

[[notes]]
title = "Flags"
id = "9ac95a50-2c13-4499-9032-7e4e413308f1"
type = "text"
parent = "2c932ba1-11cf-4e23-bbe1-a65235513872"
order = 3
icon_emoji = "🚩"
text = """Track local.txt / proof.txt and other trophies...

"""

[[notes]]
title = "Cleanup"
id = "a1cdcd2f-cfa6-4b88-b616-b6da69a31cc8"
type = "text"
parent = "2c932ba1-11cf-4e23-bbe1-a65235513872"
order = 4
icon_emoji = "🧹"
text = """Document changes to revert: accounts, tools, persistence, uploaded files...

"""

[[notes]]
title = "To Do's"
id = "e013a8e7-1d74-40fb-8419-6da7b198a462"
type = "text"
parent = "2c932ba1-11cf-4e23-bbe1-a65235513872"
order = 5
icon_emoji = "✔️"
text = ""

[[notes]]
title = "To Do X"
id = "b269afd4-5fcc-4dcf-ba29-dc225cb283f2"
type = "text"
parent = "e013a8e7-1d74-40fb-8419-6da7b198a462"
order = 1
checked = false
text = ""
