# Generated by Django 4.2.2 on 2023-06-29 06:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sysreptor.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pentestuser_is_global_archiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=256)),
                ('name', models.CharField(default='API Token', max_length=255)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=(sysreptor.utils.models.ModelDiffMixin, models.Model),
        ),
    ]
