# Generated by Django 5.0.6 on 2024-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='last_used',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
