# Generated by Django 6.0.7 on 2026-07-24 07:19

from django.db import migrations, models


def enable_admin_permissions_for_superuser_tokens(apps, schema_editor):
    APIToken = apps.get_model('users', 'APIToken')
    APIToken.objects \
        .filter(user__is_superuser=True) \
        .update(admin_permissions_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_pentestuser_can_login_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='admin_permissions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_admin_permissions_for_superuser_tokens, migrations.RunPython.noop),
    ]
