# Generated by Django 5.2.1

from itertools import batched
from uuid import UUID, uuid4

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import SESSION_KEY
from django.db import migrations, models

import sysreptor.utils.models
from sysreptor.users.backends.session import SessionStore
from sysreptor.utils.crypto.base import CryptoError


def migrate_sessions(apps, schema_editor):
    Session = apps.get_model('users', 'Session')
    PentestUser = apps.get_model('users', 'PentestUser')
    store = SessionStore()
    existing_user_ids = set(PentestUser.objects.values_list('id', flat=True))

    for batch in batched(Session.objects.all().iterator(), 500):
        for session in batch:
            if session.id is None:
                session.id = uuid4()

            try:
                data = store.decode(session.session_data)
            except (CryptoError, UnicodeDecodeError, TypeError, ValueError):
                continue
            user_id = data.get(SESSION_KEY)
            if not user_id:
                continue
            try:
                user_uuid = UUID(str(user_id))
            except (ValueError, TypeError, AttributeError):
                continue
            if user_uuid in existing_user_ids:
                session.user_id = user_uuid

        Session.objects.bulk_update(batch, ['id', 'user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pentestuser_failed_mfa_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default=sysreptor.utils.models.now, editable=False),
        ),
        migrations.AddField(
            model_name='session',
            name='updated',
            field=models.DateTimeField(auto_now=True, editable=False),
        ),
        migrations.RunPython(code=migrate_sessions, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='session',
            name='session_key_hash',
            field=models.BinaryField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
    ]
