# Generated by Django 5.2.5 on 2025-09-09 13:40

import json

from django.core.files.base import ContentFile
from django.db import migrations, models
from django.db.models.functions import Coalesce
from django.utils import timezone
from sysreptor.pentests.models import NoteType


def migrate_excalidraw(apps, schema_editor):
    ProjectExcalidrawData = apps.get_model('plugin_c50b19ffdb684a83950880ff6b6d2498', 'ProjectExcalidrawData')
    ProjectNotebookPage = apps.get_model('pentests', 'ProjectNotebookPage')
    ProjectNotebookExcalidrawFile = apps.get_model('pentests', 'ProjectNotebookExcalidrawFile')

    for e in ProjectExcalidrawData.objects.select_related('project').all():
        note = ProjectNotebookPage.objects.create(
            project=e.project,
            parent=None,
            order=e.project.notes.filter(parent=None).aggregate(max_order=Coalesce(models.Max('order'), models.Value(0)))['max_order'] + 1,
            type=NoteType.EXCALIDRAW,
            title='Excalidraw',
        )
        ProjectNotebookExcalidrawFile.objects.create(
            linked_object=note,
            file=ContentFile(content=json.dumps({'elements': e.elements}).encode(), name=f'excalidraw-{timezone.now().isoformat()}.json'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_c50b19ffdb684a83950880ff6b6d2498', '0001_initial'),
        ('pentests', '0065_notes_excalidraw'),
    ]

    operations = [
        migrations.RunPython(code=migrate_excalidraw, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ProjectExcalidrawData',
        ),
    ]
