# Generated by Django 5.2 on 2025-04-08 11:56

import itertools

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from sysreptor.utils.utils import datetime_from_date


def migrate_notifications(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    # Migrate status
    Notification.objects.filter(read=False).update(status='open')
    Notification.objects.filter(read=True).update(status='resolved')
    # Migrate active_until to visible_until
    notifications_active_until = Notification.objects \
        .filter(remotenotificationspec__active_until__isnull=False) \
        .filter(visible_until__isnull=True) \
        .select_related('remotenotificationspec')
    for batch in itertools.batched(notifications_active_until, 1000):
        for n in batch:
            n.visible_until = datetime_from_date(n.remotenotificationspec.active_until)
        Notification.objects.bulk_update(batch, ['visible_until'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationspec_instance_conditions'),
        ('pentests', '0063_alter_pentestproject_project_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationSpec',
            new_name='RemoteNotificationSpec',
        ),
        migrations.RenameModel(
            old_name='UserNotification',
            new_name='Notification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification',
            new_name='remotenotificationspec',
        ),
        migrations.AlterField(
            model_name='notification',
            name='remotenotificationspec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.remotenotificationspec'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='additional_content',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pentests.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pentests.pentestfinding'),
        ),
        migrations.AddField(
            model_name='notification',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pentests.projectnotebookpage'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pentests.pentestproject'),
        ),
        migrations.AddField(
            model_name='notification',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pentests.reportsection'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('remote', 'Remote'), ('member_added', 'Member Added'), ('finished', 'Finished'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('delete_evidence', 'Delete Evidence'), ('restore_started', 'Restore Started'), ('commented', 'Commented'), ('mentioned', 'Mentioned'), ('assigned', 'Assigned'), ('backup_missing', 'Backup Missing')], default='remote', max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(code=migrate_notifications, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
