# Generated by Django 5.2.9 on 2025-12-09 13:16

import django.db.models.deletion
import sysreptor.utils.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notificationspec_remotenotificationspec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotificationSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active_until', models.DateField(blank=True, db_index=True, null=True)),
                ('user_conditions', models.JSONField(blank=True, default=dict)),
                ('visible_for_days', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('link_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='remotenotificationspec',
            options={},
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('remote', 'Remote'), ('custom', 'Custom'), ('member', 'Member'), ('finished', 'Finished'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('assigned', 'Assigned'), ('backup_missing', 'Backup Missing')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='customnotificationspec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.customnotificationspec'),
        ),
    ]
