# Generated by Django 5.2.9 on 2025-12-09 14:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import sysreptor.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notificationspec_remotenotificationspec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotificationSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the notification displayed to users.', max_length=255)),
                ('text', models.TextField(help_text='Main notification message body displayed to users.')),
                ('link_url', models.TextField(blank=True, help_text='Optional URL where users can find more information or take action.', null=True)),
                ('active_until', models.DateField(blank=True, db_index=True, help_text='Date until which the notification remains active. Notifications are automatically hidden after this date.', null=True)),
                ('visible_for_days', models.IntegerField(blank=True, help_text='Number of days the notification remains visible after it is created for a user. When set, new users automatically receive this notification with the visibility period starting from their creation date.', null=True)),
                ('user_conditions', models.JSONField(blank=True, default=dict, help_text='User attribute conditions that determine who receives this notification. Supports filtering by permissions. Example: {"is_superuser": true} to target only superusers, or {"is_designer": false} for non-designers. Leave empty to target all users.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='remotenotificationspec',
            options={},
        ),
        migrations.AlterField(
            model_name='remotenotificationspec',
            name='active_until',
            field=models.DateField(blank=True, db_index=True, help_text='Date until which the notification remains active. Notifications are automatically hidden after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='remotenotificationspec',
            name='link_url',
            field=models.TextField(blank=True, help_text='Optional URL where users can find more information or take action.', null=True),
        ),
        migrations.AlterField(
            model_name='remotenotificationspec',
            name='text',
            field=models.TextField(help_text='Main notification message body displayed to users.'),
        ),
        migrations.AlterField(
            model_name='remotenotificationspec',
            name='title',
            field=models.CharField(help_text='Title of the notification displayed to users.', max_length=255),
        ),
        migrations.AlterField(
            model_name='remotenotificationspec',
            name='user_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='User attribute conditions that determine who receives this notification. Supports filtering by permissions. Example: {"is_superuser": true} to target only superusers, or {"is_designer": false} for non-designers. Leave empty to target all users.'),
        ),
        migrations.AlterField(
            model_name='remotenotificationspec',
            name='visible_for_days',
            field=models.IntegerField(blank=True, help_text='Number of days the notification remains visible after it is created for a user. When set, new users automatically receive this notification with the visibility period starting from their creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('remote', 'Remote'), ('custom', 'Custom'), ('member', 'Member'), ('finished', 'Finished'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('assigned', 'Assigned'), ('backup_missing', 'Backup Missing')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='customnotificationspec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.customnotificationspec'),
        ),
    ]
