# Generated by Django 5.2.7 on 2025-10-24 12:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sysreptor.utils.crypto.fields
import sysreptor.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pentests', '0065_notes_excalidraw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pentests.pentestproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LangchainCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checkpoint_ns', models.CharField(db_index=True, default='', max_length=255)),
                ('checkpoint_id', models.UUIDField(default=uuid.uuid4)),
                ('parent_checkpoint_id', models.UUIDField(blank=True, null=True)),
                ('metadata', sysreptor.utils.crypto.fields.EncryptedField(base_field=models.BinaryField(), blank=True, default=dict, editable=True)),
                ('checkpoint_type', models.CharField(max_length=255)),
                ('checkpoint', sysreptor.utils.crypto.fields.EncryptedField(base_field=models.BinaryField(), editable=True)),
                ('pending_writes_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_writes', sysreptor.utils.crypto.fields.EncryptedField(base_field=models.BinaryField(), blank=True, editable=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='ai.chatthread')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
                'unique_together': {('thread', 'checkpoint_ns', 'checkpoint_id')},
            },
        ),
    ]
