# Generated by Django 4.1.3 on 2022-12-17 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportcreator_api.archive.crypto.fields
import reportcreator_api.users.querysets
import reportcreator_api.utils.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_db_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=reportcreator_api.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method_type', models.CharField(choices=[('totp', 'TOTP'), ('fido2', 'FIDO2'), ('backup', 'Backup codes')], max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('data', reportcreator_api.archive.crypto.fields.EncryptedField(base_field=models.JSONField(), editable=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
            bases=(reportcreator_api.utils.models.ModelDiffMixin, models.Model),
        ),
    ]
