# Generated by Django 4.1.3 on 2023-01-04 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportcreator_api.utils.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pentestuser_is_system_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=reportcreator_api.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
                'unique_together': {('provider', 'identifier')},
            },
            bases=(reportcreator_api.utils.models.ModelDiffMixin, models.Model),
        ),
    ]
