# Generated by Django 5.0.6 on 2024-06-17 11:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

import sysreptor.utils.models
from sysreptor.api_utils.models import BackupLogType


def migrate_setup_log(apps, schema_editor):
    BackupLog = apps.get_model('api_utils', 'BackupLog')
    PentestUser = apps.get_model('users', 'PentestUser')

    instance_setup_date = PentestUser.objects.aggregate(setup_date=models.Min('created'))['setup_date'] or timezone.now()
    BackupLog.objects.create(
        created=instance_setup_date,
        type=BackupLogType.SETUP,
        user=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api_utils', '0001_languagetool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=sysreptor.utils.models.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('setup', 'Setup'), ('backup', 'Backup'), ('restore', 'Restore')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.RunPython(code=migrate_setup_log, reverse_code=migrations.RunPython.noop),
    ]
