# Generated by Django 5.1.6 on 2025-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_utils', '0002_backuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbConfigurationEntry',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
