# Generated by Django 5.2.4 on 2025-07-29 12:35

from django.db import migrations, models


def migrate_backuplogtype(apps, schema_editor):
    BackupLog = apps.get_model('api_utils', 'BackupLog')
    BackupLog.objects.filter(type='backup').update(type='backup_finished')


def reverse_migrate_backuplogtype(apps, schema_editor):
    BackupLog = apps.get_model('api_utils', 'BackupLog')
    BackupLog.objects.filter(type='backup_finished').update(type='backup')


class Migration(migrations.Migration):

    dependencies = [
        ('api_utils', '0003_dbconfigurationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='type',
            field=models.CharField(choices=[('setup', 'Setup'), ('backup_started', 'Backup Started'), ('backup_finished', 'Backup Finished'), ('restore', 'Restore')], max_length=20),
        ),
        migrations.RunPython(code=migrate_backuplogtype, reverse_code=reverse_migrate_backuplogtype),
    ]
